from flask import render_template,url_for,flash,request
from realestate import app,db,mail
from models import ContactForm
from flask_mail import Message
import requests





@app.route('/')
def hello_world():
    return 'Hello, World!'

@app.route('/login')
def login():
    return render_template('login.html')

@app.route('/home')
def index():
    return render_template('index.html')

@app.route('/contactus',methods=['GET','POST'])
def contacts():
    if request.method == "GET":
        return render_template('contacts.html')
    else:
        form = ContactForm()
        name = request.form['personname']
        mobile = request.form['mobile']
        email = request.form['email']
        message = request.form['textarea']
        realestate = ContactForm(name=name,email=email,mobile=mobile,message=message)
        db.session.add(realestate)
        db.session.commit()
        if email == None:
            msg = Message('Dear Muruganantham, /n {}'.format(message), sender = "autogenerated@gmail.com", recipients = ['vrmconstructionrealestate@gmail.com'])
            msg.body = ("Dear Muruganantham, {} /n Regards /n{}/n{}".format(message,name,mobile))
        else:
            msg = Message('Client Notification:- {}'.format(name), sender = email, recipients = ['vrmconstructionrealestate@gmail.com'])
            msg.body = ("Dear Muruganantham, {} /n Regards /n{}/n{}".format(message,name,mobile))
            flash('Email has been sent to VRM Team we will contact you shortly')
            mail.send(msg)
            url = "https://www.fast2sms.com/dev/bulk"
            payload = "sender_id=FSTSMS&message= {} {} &language=english&route=p&numbers=8939967677,9894272239,7339575987".format(message,name)
            headers = {
            'authorization': "7bjDWt9sEzh6lAuCQZrcx28Op1giIT4HUkwXnqL3MeRJFdf0aoHxBLNMsykRAw0zeihYCK6rJ1QEolUq",
            'Content-Type': "application/x-www-form-urlencoded",
            'Cache-Control': "no-cache",
            }
            response = requests.request("POST", url, data=payload, headers=headers)
            print(response.text)
            print("Email Sent")
            

        return render_template('contacts.html')


    
    return render_template('contacts.html')



